// Photos locales de repli — utilisées quand Supabase n'est pas configuré
// ou quand une section ne contient encore aucune photo en base.
// Chaque entrée suit la forme { url, caption } retournée par getPhotos().

export const defaultPhotos = {
  sanitaire: [
    { url: '/images/photos/sanitaire/sanitaire-01.jpg', caption: '' },
    { url: '/images/photos/sanitaire/sanitaire-02.jpg', caption: '' },
    { url: '/images/photos/sanitaire/sanitaire-03.jpg', caption: '' },
  ],
  scolaire: [
    { url: '/images/photos/scolaire/scolaire-01.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-02.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-03.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-04.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-05.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-06.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-07.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-08.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-09.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-10.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-11.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-12.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-13.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-14.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-15.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-16.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-17.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-18.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-19.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-20.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-21.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-22.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-23.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-24.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-25.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-26.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-27.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-28.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-29.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-30.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-31.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-32.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-33.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-34.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-35.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-36.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-37.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-38.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-39.jpg', caption: '' },
    { url: '/images/photos/scolaire/scolaire-40.jpg', caption: '' },
  ],
  jeux: [
    { url: '/images/photos/jeux/jeux-01.jpg', caption: '' },
    { url: '/images/photos/jeux/jeux-02.jpg', caption: '' },
    { url: '/images/photos/jeux/jeux-03.jpg', caption: '' },
    { url: '/images/photos/jeux/jeux-04.jpg', caption: '' },
    { url: '/images/photos/jeux/jeux-05.jpg', caption: '' },
  ],
  don: [
    { url: '/images/photos/don/don-01.jpg', caption: '' },
    { url: '/images/photos/don/don-02.jpg', caption: '' },
    { url: '/images/photos/don/don-03.jpg', caption: '' },
    { url: '/images/photos/don/don-04.jpg', caption: '' },
    { url: '/images/photos/don/don-05.jpg', caption: '' },
    { url: '/images/photos/don/don-06.jpg', caption: '' },
    { url: '/images/photos/don/don-07.jpg', caption: '' },
    { url: '/images/photos/don/don-08.jpg', caption: '' },
    { url: '/images/photos/don/don-09.jpg', caption: '' },
    { url: '/images/photos/don/don-10.jpg', caption: '' },
    { url: '/images/photos/don/don-11.jpg', caption: '' },
    { url: '/images/photos/don/don-12.jpg', caption: '' },
    { url: '/images/photos/don/don-13.jpg', caption: '' },
    { url: '/images/photos/don/don-14.jpg', caption: '' },
    { url: '/images/photos/don/don-15.jpg', caption: '' },
    { url: '/images/photos/don/don-16.jpg', caption: '' },
    { url: '/images/photos/don/don-17.jpg', caption: '' },
    { url: '/images/photos/don/don-18.jpg', caption: '' },
    { url: '/images/photos/don/don-19.jpg', caption: '' },
    { url: '/images/photos/don/don-20.jpg', caption: '' },
    { url: '/images/photos/don/don-21.jpg', caption: '' },
    { url: '/images/photos/don/don-22.jpg', caption: '' },
    { url: '/images/photos/don/don-23.jpg', caption: '' },
    { url: '/images/photos/don/don-24.jpg', caption: '' },
    { url: '/images/photos/don/don-25.jpg', caption: '' },
    { url: '/images/photos/don/don-26.jpg', caption: '' },
    { url: '/images/photos/don/don-27.jpg', caption: '' },
    { url: '/images/photos/don/don-28.jpg', caption: '' },
    { url: '/images/photos/don/don-29.jpg', caption: '' },
    { url: '/images/photos/don/don-30.jpg', caption: '' },
    { url: '/images/photos/don/don-31.jpg', caption: '' },
    { url: '/images/photos/don/don-32.jpg', caption: '' },
    { url: '/images/photos/don/don-33.jpg', caption: '' },
    { url: '/images/photos/don/don-34.jpg', caption: '' },
    { url: '/images/photos/don/don-35.jpg', caption: '' },
    { url: '/images/photos/don/don-36.jpg', caption: '' },
    { url: '/images/photos/don/don-37.jpg', caption: '' },
    { url: '/images/photos/don/don-38.jpg', caption: '' },
    { url: '/images/photos/don/don-39.jpg', caption: '' },
    { url: '/images/photos/don/don-40.jpg', caption: '' },
    { url: '/images/photos/don/don-41.jpg', caption: '' },
    { url: '/images/photos/don/don-42.jpg', caption: '' },
    { url: '/images/photos/don/don-43.jpg', caption: '' },
    { url: '/images/photos/don/don-44.jpg', caption: '' },
    { url: '/images/photos/don/don-45.jpg', caption: '' },
  ],
  partenaires: [
    { url: '/images/partenaires/mama-yovo.jpg', caption: 'Mama Yovo' },
  ],
  hero: [
    { url: '/images/photos/don/don-01.jpg', caption: 'Des infrastructures au service des écoles' },
    { url: '/images/photos/scolaire/scolaire-01.jpg', caption: 'Des kits scolaires pour chaque enfant' },
    { url: '/images/photos/sanitaire/sanitaire-01.jpg', caption: "L'accès aux soins pour tous" },
  ],
};
